#!/bin/bash
if test $1 = "-h" 2>/dev/null
then
    cat csv2html-help.txt
else
    if $(test -z $1)
    then
	
        #lecture de la première ligne
	read l

        # début tableau HTML
	echo \<table border=1\>


        #en-tête du tableau - première ligne du fichier .csv
	echo "<tr><th>$(echo $l | sed -r -e 's!;$!</th></tr>!' -e 's!;!</th><th>!g')" 

        #reste du fichier .csv
	sed  -r -e '2,$ s!;$!</td></tr>!g' -e 's!;!</td><td>!g' -e 's!^!<tr><td>!'

        #fin tableau HTML
	echo \</table\>

    #délimiteur avec l'argument
    elif $(test $1 == "-d")
    then
	shift
	if $(test -z $1)
	then
	    echo vous devez specifier un delimiteur
	else
	    #lecture de la première ligne
	    read l

            # début tableau HTML
	    echo \<table border=1\>

            #en-tête du tableau - première ligne du fichier .csv
	    echo "<tr><th>$(echo $l | sed -r -e 's!$!</th></tr>!' -e 's!'$1'!</th><th>!g')" 

            #reste du fichier .csv
	    sed  -r -e '2,$ s!'$1'$!</td></tr>!g' -e 's!'$1'!</td><td>!g' -e 's!^!<tr><td>!'

            #fin tableau HTML
	    echo \</table\>
	fi

    #tri avec le numéro de colonne
    elif $(test $1 == "-s")
    then
	shift
	if $(test -z $1)
	then
	    echo vous devez entrer le numero de la colonne a trier
	else
	    #lecture de la première ligne
	    read l

            # début tableau HTML
	    echo \<table border=1\>


            #en-tête du tableau - première ligne du fichier .csv
	    echo "<tr><th>$(echo $l | sed -r -e 's!;$!</th></tr>!' -e 's!;!</th><th>!g')" 

            #reste du fichier .csv
	    sort -d -t ';' -k $1 | sed  -r -e '2,$ s!;$!</td></tr>!g' -e 's!;!</td><td>!g' -e 's!^!<tr><td>!'

            #fin tableau HTML
	    echo \</table\>
	fi

    #tri avec le nom de la colonne
    elif $(test $1 == "-S")
    then
	shift
	if $(test -z $1)
	then
	    echo vous devez entrer le nom de la colonne a trier
	else
            #lecture de la première ligne
	    read l
	    cpt=1
	    firstligne=$(echo $l | sed -r -e 's!;! !g')
	    #recherche du numero de la colonne correspondant à l'argument
	    for i in $firstligne
	    do
		if test $1 == $i
		then
		    mot=$i
		    break
		fi
		let cpt++
	    done

	    #on viens de récupérer le cpt, faire maintenant un tri sur la colonne cpt
	    
            # début tableau HTML
	    echo \<table border=1\>

	    #en-tête du tableau - première ligne du fichier .csv
	    echo "<tr><th>$(echo $l | sed -r -e 's!;$!</th></tr>!' -e 's!;!</th><th>!g')"

            #reste du fichier .csv
	    sort -d -t ';' -k $cpt | sed  -r -e '2,$ s!;$!</td></tr>!g' -e 's!;!</td><td>!g' -e 's!^!<tr><td>!'

            #fin tableau HTML
	    echo \</table\>
	fi
    fi
fi