#!/bin/bash
#set -x 
if test $1 = "-h"
then
    cat remplace-par-help.txt
else
    #cas sans argument en entrée
    if $(test -z $1)
    then
	echo "vous devez spécifier un fichier en argument"
    else
        #cas avec argument

        #on affiche le modèle jusqu'à --DEBUT exclu
	cat $1 | sed -e '/--DEBUT--/,$ D'

        #on affiche le corps
	cat

        #on affiche le modèle depuis --FIN
	cat $1 | sed -e '1, /--FIN--/ D'
    fi
fi