#!/bin/bash
#set -x
if test $1 = "-h"
then
    cat remplace-par-wiki-help.txt
else
    #cas sans argument en entrée
    if $(test -z $1)
    then
	echo "vous devez spécifier un fichier en argument"
    else
        #cas avec argument

        #on applique le script remplace-par avec notre argument et on effectue les modifications sur le contenu final, nécessite remplace-par dans le même dossier
	./remplace-par $1 | sed -r -e 's!\* !\<\/strong\> !g' -e 's!\*!\<strong\>!g' -e 's!\" !\<\/em\> !g' -e 's!\"!\<em\>!g'
    fi
fi