#!/usr/bin/perl

if(@ARGV){
    
    use Socket;

    socket(SERVEUR,PF_INET,SOCK_STREAM,getprotobyname('tcp'));
    setsockopt(SERVEUR,SOL_SOCKET, SO_REUSEADDR,1);

    $mon_adresse = sockaddr_in ("8080",INADDR_ANY);

    bind(SERVEUR, $mon_adresse) || die ("bind");

    listen (SERVEUR, SOMAXCONN) || die ("listen");

    accept(CLIENT,SERVEUR) || die ("accept");
    select(CLIENT);

    for($i =0 ; $i < $ARGV[0] ; $i++){
	print "bonjour\n";
    }

    close(CLIENT);
    close(SERVEUR);
}else{
    print "erreur d'argument";
}
